# processes master DB of individual plays by player, collecting them into
#   sums of stats per game
# input: list of plays by player code generated by SingleSeason
# output: list of players with per-game totals

class GameSums
  def initialize
    @playerList
  end

  def load_plays
  end

  def sum_game
  end

  def get_game
  end
end
